services:
  externo:
    container_name: externo
    image: externo
    environment:
      POSTGRES_PASSWORD: senha
    build: 
      context: ./external-service
    ports: 
      - "8081:8080"

  aluguel:
    container_name: aluguel
    image: aluguel
    build:
      context: ./aluguel-service
    ports:
      - "8082:3000"

  equipamento:
    container_name: equipamento
    image: equipamento
    environment:
      POSTGRES_PASSWORD: senha
    build:
      context: ./equipamento-service
    ports:
      - "8083:8080"

  dbExterno:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: externoDB
    ports:
      - "5432:5432"
    volumes:
      - externo_data:/var/lib/postgresql/data

  dbEquipamento:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: equipamentoDB
    ports:
      - "5433:5432"
    volumes:
      - equipamento_data:/var/lib/postgresql/data

volumes:
  externo_data:
  equipamento_data