# ===================================================================
# CONFIGURA��O DE PRODU��O (prod) - Para deploy no Heroku
# ===================================================================

# Configura��o do Banco de Dados PostgreSQL (fornecido pelo Heroku)
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# Configura��o do JPA/Hibernate para produ��o
# 'validate' � mais seguro que 'update' em produ��o.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Desabilita o console do H2 em produ��o por seguran�a.
spring.h2.console.enabled=false